name       : perl-lwp-protocol-https
version    : '6.11'
release    : 9
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/LWP-Protocol-https-6.11.tar.gz : 0132ddbf03661565ca85050f2a5094fb9263cbbc3ccb1a4d9c41ac9bb083b917
homepage   : https://metacpan.org/pod/LWP::Protocol::https
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : LWP::Protocol::https - Provide https support for LWP::UserAgent
description: |
    The LWP::Protocol::https module provides support for using https schemed URLs with LWP. This module is a plug-in to the LWP protocol handling, so you don't use it directly. Once the module is installed LWP is able to access sites using HTTP over SSL/TLS.
rundeps    :
    - perl-io-socket-ssl
    - perl-net-http
setup      : |
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
