name       : perl-lwp-protocol-https
version    : '6.10'
release    : 8
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/LWP-Protocol-https-6.10.tar.gz : cecfc31fe2d4fc854cac47fce13d3a502e8fdfe60c5bc1c09535743185f2a86c
homepage   : https://metacpan.org/pod/LWP::Protocol::https
license    : Artistic-1.0-Perl
component  : programming.perl
summary    : LWP::Protocol::https - Provide https support for LWP::UserAgent
description: |
    The LWP::Protocol::https module provides support for using https schemed URLs with LWP. This module is a plug-in to the LWP protocol handling, so you don't use it directly. Once the module is installed LWP is able to access sites using HTTP over SSL/TLS.
rundeps    :
    - perl-io-socket-ssl
    - perl-net-http
setup      : |
    %patch -p1 < $pkgfiles/lwp-protocol-https-cert-file.patch
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
