name       : perl-lwp-protocol-https
version    : 6.07
release    : 4
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/LWP-Protocol-https-6.07.tar.gz : 522cc946cf84a1776304a5737a54b8822ec9e79b264d0ba0722a70473dbfb9e7
license    : Artistic-Perl-1.0
component  : programming.perl
summary    : Provides https support for LWP::UserAgent
description: |
    Provides https support for LWP::UserAgent
rundeps    :
    - perl-io-socket-ssl
    - perl-net-http
setup      : |
    %patch -p1 < $pkgfiles/lwp-protocol-https-cert-file.patch
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
