name       : perl-lwp-protocol-https
version    : '6.09'
release    : 7
source     :
    - https://cpan.metacpan.org/authors/id/O/OA/OALDERS/LWP-Protocol-https-6.09.tar.gz : 16cfe1a511690b066db5667c8714802ee2b9c5d28a31a3e7bd36fbc70a3af592
homepage   : https://metacpan.org/pod/LWP::Protocol::https
license    : Artistic-Perl-1.0
component  : programming.perl
summary    : Provides https support for LWP::UserAgent
description: |
    Provides https support for LWP::UserAgent
rundeps    :
    - perl-io-socket-ssl
    - perl-net-http
setup      : |
    %patch -p1 < $pkgfiles/lwp-protocol-https-cert-file.patch
    %perl_setup
build      : |
    %perl_build
install    : |
    %perl_install
